#!/bin/bash
show_menu(){
    normal=`echo "\033[m"`
    menu=`echo "\033[36m"` #Blue
    number=`echo "\033[33m"` #yellow
    fggreen=`echo "\e[92m"`
    fgred=`echo "\033[31m"`
    
    version="1.6"

    mitems=(
           "Medium - Defense Evasion via Masquerading"
           "Critical - Defense Evasion via Rootkit"
           "High - Execution via Command-Line Interface"
           "High - Exfiltration Over Alternative Protocol"
           "High -$fggreen Command & Control via Remote Access Protocol"
           "High - Collection via Automated Collection"
           "High - Credential Access via Credential Dumping"
           "High -$fggreen Malware Linux Trojan"
           )

    edir='/home/eval/bin/'

    eitems=(
           "Defense_Evasion_via_Masquerading.sh"
           "Defense_Evasion_via_Rootkit.sh"
           "Execution_via_Command-Line_Interface.sh"
           "Exfiltration_via_Exfiltration_Over_Alternative_Protocol.sh > /dev/null 2>&1"
           "Command_Control_via_Remote_Access.sh"
           "Collection_via_Automated_Collection.sh"
	   "Credential_Access_via_Credential_Dumping.sh" 
           "Malware_Linux_Trojan.sh"
           )
    numitems=${#mitems[@]}

    printf "${fgred}V${version}${normal}\n"
    printf "\n${menu}     Select one of the following TTPs${normal}\n"
    printf "\n${menu}*********************************************${normal}\n"

    for (( i=1; i<=$numitems; i++ ))
    do
	    j=i-1
	    printf "${menu}**${number} ${i})${menu} ${mitems[$j]} ${normal}\n"
    done

    printf "\n"
    printf "${menu}**${number} e)${menu} Exit to Container shell${normal}\n"
    printf "${menu}**${number} x)${menu} Exit Container${normal}\n"
    printf "${menu}*********************************************${normal}\n"
    printf "Please enter a menu option and enter: "
    read  opt
}

after_exec(){
	read -p "Press enter to continue";
	clear;
	show_menu;
}

option_picked(){
    msgcolor=`echo "\033[01;31m"` # bold red
    normal=`echo "\033[00;00m"` # normal white
    message=${@:-"${normal}Error: No message passed"}
    printf "${msgcolor}${message}${normal}\n"
}

clear
show_menu
while  true
    do
    if [ $opt = '' ]; then
      exit;
    else
      case $opt in
        [1-${#mitems[@]}]) clear;
	    m=$opt-1
	    option_picked "$opt - ${mitems[$m]}"
	    $edir${eitems[$m]};
            after_exec;
        ;;

        e) clear;
            option_picked "Type exit to return to menu";
            /bin/bash;
            show_menu;
        ;;

        x)exit;
        ;;

        \n)exit;
        ;;

        *)clear;
            option_picked "Pick a valid option from the menu";
            show_menu;
        ;;
      esac
    fi
done
