name: Multi-arch build

on: push

env:
  IMAGE_TAG: latest
  IMAGE_REGISTRY: quay.io
  IMAGE_REPOSITORY: crowdstrike/detection-container

jobs:
  build-multiarch-image:
    name: Build multi-architecture image
    runs-on: ubuntu-latest

    steps:
      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64,linux/amd64,linux/s390x,linux/ppc64le

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Setup Cross Compile Dockerfile
        run: sed -e '1 s/\(^FROM\)/FROM --platform=$\{BUILDPLATFORM\}/; t' -e ' 1,// s//FROM --platform=$\{BUILDPLATFORM\}/' Dockerfile > Dockerfile.cross

      - name: Build and push
        id: build_image_multiarch
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.cross
          platforms: linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
          push: true
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Check manifest
        run: |
          docker buildx imagetools inspect ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${{ env.IMAGE_TAG }}
